<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lawyer;
use Illuminate\Support\Facades\DB;

class LawyerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lawyers')->truncate();
        
        $lawyers = [
            [
                'name' => 'Dr. Dzikri Murtadlo, S.H., M.H.',
                'specialization' => ['Contract Law', 'Corporate Law'],
                'location' => 'Jakarta',
                'rating' => 4.8,
                'experience_years' => 15,
                'image_url' => 'https://randomuser.me/api/portraits/men/32.jpg',
                'email' => 'ahmad.fauzi@legalfirm.com',
                'phone' => '+62812345678',
                'available' => true,
            ],
            [
                'name' => 'Siti Nurhaliza, S.H.',
                'specialization' => ['Family Law', 'Civil Law'],
                'location' => 'Bandung',
                'rating' => 4.5,
                'experience_years' => 8,
                'image_url' => 'https://randomuser.me/api/portraits/women/44.jpg',
                'email' => 'siti.nurhaliza@legalfirm.com',
                'phone' => '+62823456789',
                'available' => true,
            ],
            [
                'name' => 'Budi Santoso, S.H., LL.M.',
                'specialization' => ['Criminal Law', 'Cyber Law'],
                'location' => 'Surabaya',
                'rating' => 4.9,
                'experience_years' => 12,
                'image_url' => 'https://randomuser.me/api/portraits/men/67.jpg',
                'email' => 'budi.santoso@legalfirm.com',
                'phone' => '+62834567890',
                'available' => true,
            ],
            [
                'name' => 'Maya Wijaya, S.H., M.Kn.',
                'specialization' => ['Property Law', 'Notary'],
                'location' => 'Jakarta',
                'rating' => 4.7,
                'experience_years' => 10,
                'image_url' => 'https://randomuser.me/api/portraits/women/22.jpg',
                'email' => 'maya.wijaya@legalfirm.com',
                'phone' => '+62845678901',
                'available' => false,
            ],
            [
                'name' => 'Reza Pratama, S.H.',
                'specialization' => ['Labor Law', 'Immigration Law'],
                'location' => 'Medan',
                'rating' => 4.3,
                'experience_years' => 5,
                'image_url' => 'https://randomuser.me/api/portraits/men/45.jpg',
                'email' => 'reza.pratama@legalfirm.com',
                'phone' => '+62856789012',
                'available' => true,
            ],
            [
                'name' => 'Dewi Kartika, S.H., M.H.',
                'specialization' => ['Intellectual Property', 'Business Law'],
                'location' => 'Jakarta',
                'rating' => 4.9,
                'experience_years' => 14,
                'image_url' => 'https://randomuser.me/api/portraits/women/33.jpg',
                'email' => 'dewi.kartika@legalfirm.com',
                'phone' => '+62876543210',
                'available' => true,
            ],
            [
                'name' => 'Anisa Rahma, S.H., LL.M.',
                'specialization' => ['Environmental Law', 'International Law'],
                'location' => 'Yogyakarta',
                'rating' => 4.7,
                'experience_years' => 11,
                'image_url' => 'https://randomuser.me/api/portraits/women/64.jpg',
                'email' => 'anisa.rahma@legalfirm.com',
                'phone' => '+62856432198',
                'available' => true,
            ],
            [
                'name' => 'Dimas Prayoga, S.H., M.Kn.',
                'specialization' => ['Tax Law', 'Corporate Law'],
                'location' => 'Jakarta',
                'rating' => 4.5,
                'experience_years' => 7,
                'image_url' => 'https://randomuser.me/api/portraits/men/23.jpg',
                'email' => 'dimas.prayoga@legalfirm.com',
                'phone' => '+62813765432',
                'available' => false,
            ],
            [
                'name' => 'Linda Susanti, S.H.',
                'specialization' => ['Family Law', 'Mediation'],
                'location' => 'Bandung',
                'rating' => 4.4,
                'experience_years' => 6,
                'image_url' => 'https://randomuser.me/api/portraits/women/29.jpg',
                'email' => 'linda.susanti@legalfirm.com',
                'phone' => '+62878123456',
                'available' => true,
            ],
            [
                'name' => 'Agus Darmawan, S.H., M.H.',
                'specialization' => ['Criminal Law', 'Human Rights'],
                'location' => 'Semarang',
                'rating' => 4.8,
                'experience_years' => 13,
                'image_url' => 'https://randomuser.me/api/portraits/men/42.jpg',
                'email' => 'agus.darmawan@legalfirm.com',
                'phone' => '+62815987654',
                'available' => true,
            ],
            [
                'name' => 'Putri Indah, S.H., LL.B.',
                'specialization' => ['Real Estate Law', 'Contract Law'],
                'location' => 'Surabaya',
                'rating' => 4.2,
                'experience_years' => 4,
                'image_url' => 'https://randomuser.me/api/portraits/women/57.jpg',
                'email' => 'putri.indah@legalfirm.com',
                'phone' => '+62822345678',
                'available' => true,
            ],
            [
                'name' => 'Bambang Sutrisno, S.H., MBA.',
                'specialization' => ['Banking Law', 'Finance Law'],
                'location' => 'Jakarta',
                'rating' => 4.6,
                'experience_years' => 16,
                'image_url' => 'https://randomuser.me/api/portraits/men/37.jpg',
                'email' => 'bambang.sutrisno@legalfirm.com',
                'phone' => '+62857123456',
                'available' => true,
            ],
            [
                'name' => 'Ratna Dewi, S.H., CLA.',
                'specialization' => ['Labor Law', 'Employment Law'],
                'location' => 'Denpasar',
                'rating' => 4.5,
                'experience_years' => 8,
                'image_url' => 'https://randomuser.me/api/portraits/women/76.jpg',
                'email' => 'ratna.dewi@legalfirm.com',
                'phone' => '+62896543210',
                'available' => false,
            ],
            [
                'name' => 'Wisnu Perdana, S.H., M.H.',
                'specialization' => ['Constitutional Law', 'Administrative Law'],
                'location' => 'Medan',
                'rating' => 4.7,
                'experience_years' => 12,
                'image_url' => 'https://randomuser.me/api/portraits/men/91.jpg',
                'email' => 'wisnu.perdana@legalfirm.com',
                'phone' => '+62817654321',
                'available' => true,
            ],
            [
                'name' => 'Tiara Nuraini, S.H.',
                'specialization' => ['Immigration Law', 'International Law'],
                'location' => 'Makassar',
                'rating' => 4.3,
                'experience_years' => 5,
                'image_url' => 'https://randomuser.me/api/portraits/women/81.jpg',
                'email' => 'tiara.nuraini@legalfirm.com',
                'phone' => '+62812345987',
                'available' => true,
            ],
            [
                'name' => 'Andika Pratama, S.H., LL.M.',
                'specialization' => ['Cyber Law', 'Intellectual Property'],
                'location' => 'Bandung',
                'rating' => 4.8,
                'experience_years' => 10,
                'image_url' => 'https://randomuser.me/api/portraits/men/18.jpg',
                'email' => 'andika.pratama@legalfirm.com',
                'phone' => '+62878654321',
                'available' => true,
            ],
            [
                'name' => 'Nadia Ayu, S.H., M.Kn.',
                'specialization' => ['Notary', 'Property Law'],
                'location' => 'Jakarta',
                'rating' => 4.6,
                'experience_years' => 9,
                'image_url' => 'https://randomuser.me/api/portraits/women/13.jpg',
                'email' => 'nadia.ayu@legalfirm.com',
                'phone' => '+62819876543',
                'available' => true,
            ],
            [
                'name' => 'Rudy Hermawan, S.H.',
                'specialization' => ['Business Law', 'Mergers and Acquisitions'],
                'location' => 'Surabaya',
                'rating' => 4.5,
                'experience_years' => 7,
                'image_url' => 'https://randomuser.me/api/portraits/men/28.jpg',
                'email' => 'rudy.hermawan@legalfirm.com',
                'phone' => '+62898765432',
                'available' => true,
            ],
        ];

        foreach ($lawyers as $lawyer) {
            Lawyer::create($lawyer);
        }
    }
}

